### ISSUE TITLE
JOSS Review: [Suggestion] examples/lorentz.py is better formatted as a jupyter notebook

### ISSUE THREAD

**Issue by ayush9pandey** [finsberg/gotranx#110]
The lorentz.py is a great example to use as a tutorial for the package. However, it contains multiple print statements to show various features of the tool. For such files, jupyter notebook is a better visual, in my opinion. It could replace the lorentz.py file or can be given as an alternate.

**Comment by finsberg** [comment]
I agree that jupyter notebooks are good for this, and in the documentation (i.e https://finsberg.github.io/gotranx/examples/lorentz.html) the file is actually converted to a notebook using [`jupytext`](https://jupytext.readthedocs.io/en/latest/) before is i passed to JupyterBook to, see https://github.com/finsberg/gotranx/blob/main/_config.yml#L38-L41

I prefer to keep it as a python file, because it is much cleaner with version control.

**Comment by ayush9pandey** [comment]
Did not see lorentz.html! Thanks.
