### ISSUE TITLE
[JOSS-Review] Paper related comments

### ISSUE THREAD

**Issue by HaoZeke** [finsberg/gotranx#142]
Both #26 and #105 should be completed since they are part of the functionality listed in the paper.
Additionally, I don't see a clear note on what remains to be implemented from `gotran` (and should be in the publication).
It is OK if the tasks cannot be completed but then they must not be noted in the publication (e.g. if `myokit` units are buggy then perhaps not mentioning `myokit` for this version is best).

**Comment by HaoZeke** [comment]
Part of https://github.com/openjournals/joss-reviews/issues/7063

**Comment by finsberg** [comment]
@HaoZeke Thanks for your feedback on this. 

Regarding #26, this a minor issue that don't really affect the functionality much. The main usage for `gotranx` is converting from CellML using `myokit`, in which the unit conversion works fine, not the other way around. 

Regarding #105, we already test the functionality in the documentation (note that the documentation generated here: https://finsberg.github.io/gotranx/examples/new-language/main.html actually runs the code on each push to the repo), so what is missing is adding unit tests for this functionality (we already have integration tests).

Regarding what remains to be implemented from `gotran`, there is a roadmap to be found here: https://finsberg.github.io/gotranx/docs/roadmap.html, but I have no intention to complete this in the near future. This will take years to complete. It is also my understanding that in order to be accepted for a JOSS publication, you don't need to have all the functionality that you want to implement already implemented. 

With this in mind I hope you agree that we can close this issue and proceed with accepting the paper for JOSS.

**Comment by finsberg** [comment]
@HaoZeke I have now changed the wording in the paper and added unit tests for `jax` in https://github.com/finsberg/gotranx/pull/144. Please let me know if you think it needs additional clarification.

**Comment by HaoZeke** [comment]
LGTM now, thanks, will continue with the rest of the checklist.
